version: '3.4'
services:
  modelling:
    build:
      context: .
      dockerfile: Dockerfile.modelling
    ports:
      - "8888:8888"
    ipc: host
    volumes:
      - "$DATA_DIR:/workspace/data"
      - "$OUTPUT_DIR:/workspace/outputs"
      - "$NOTEBOOK_DIR:/workspace/notebooks"
      - "$SAVE_DIR:/workspace/saves"
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - "$MLRUNS_DIR:/mlruns"
